server:
  port: 7770
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baizhantang/remote_config
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
